### ISSUE TITLE
Apple Silicon Release

### ISSUE THREAD

**Issue by DomT4** [duckduckgo/privacy-essentials-safari#10]
Hi there!

Is there any chance of a new release soon with a universal _(x86_64 & arm64)_ binary for the newish MacBooks with Apple Silicon/M1 chips in them? It looks like the existing code compiles & at least seems to run fine locally on ARM64 when using Xcode 12.4 on macOS Big Sur so I think it'd just require a new release cut using a recent version of Xcode?

```
~> file /Applications/DuckDuckGo\ Privacy\ Essentials.app/Contents/MacOS/DuckDuckGo\ Privacy\ Essentials
/Applications/DuckDuckGo Privacy Essentials.app/Contents/MacOS/DuckDuckGo Privacy Essentials: Mach-O 64-bit executable arm64
```

**Comment by tomasstrba** [comment]
Thanks @DomT4! 1.4.4. is released as a universal binary, should be reviewed and available soon.

**Comment by DomT4** [comment]
Thanks @tomasstrba! Appreciate the quick turnaround on shipping 1.4.4 🍾
