### ISSUE TITLE
DuckDuckGo Privacy Essentials is Using Significant Energy

### ISSUE THREAD

**Issue by megaslav** [duckduckgo/privacy-essentials-safari#17]
I have a MacBook 2020 M1 16GB and DuckDuckGo Privacy Essentials installed for Safari. 
For the last couple of days I noticed that the battery is draining quite fast. Clicking on the battery icon up on top, the system informs me that DuckDuckGo Privacy Essentials is Using Significant Energy (attached image below).

Clicking there, shows the activity monitor, where I don't see anything unusual (attached a screenshot below).

Today, by using the laptop normally at 50% brightness and browsing online on WiFi, I went from 85% to 35% in less than 3 hours, when usually I run it for 15+ hours before reaching critical levels of battery.

Found just one mention of this issue online, a 2 years old post on reddit:

https://www.reddit.com/r/duckduckgo/comments/ezarnh/energy_use_by_privacy_essentials/

Perhaps the issue is somewhere else, but I report just in case. Please advise.

![image](https://user-images.githubusercontent.com/3853985/142418748-d6370d27-b91a-4a6a-804c-404c023bf4f1.png)

![image](https://user-images.githubusercontent.com/3853985/142418042-a96ade4a-5115-4f92-979c-190ba691f07e.png)

**Comment by brindy** [comment]
Hi - thanks for raising this and sorry it's taken a while to reply. The dashboard is currently under development and will have some significant improvements in the next few months.  While we haven't observed this problem directly I'm confident the work we're doing will help resolve this.  I'm going to close this out for now.  Keep an eye on the App Store for a new version in the next few weeks and please report back if you still see problems.

Thanks!
