### ISSUE TITLE
Add more details on Privacy Practices section

### ISSUE THREAD

**Issue by amdelamar** [duckduckgo/privacy-essentials-safari#18]
The Privacy Practices section doesn't have any details for different grades.

Example:
![image](https://user-images.githubusercontent.com/18532924/144518542-b5e30c61-9851-4214-8150-22bc3b63a4e2.png)
vs
![image](https://user-images.githubusercontent.com/18532924/144518559-73d628c1-9ab7-4a1b-a2a0-53c3f01fe0b7.png)
vs
![image](https://user-images.githubusercontent.com/18532924/144518629-6f9d5817-b1a2-4b98-b214-2c0975e50b09.png)

Can we add an expandable > arrow to show more details?

**Comment by brindy** [comment]
Hi, thanks for getting in touch and sorry for taking so long to reply.  

We're updating our dashboard across all our products so this will be resolved with those changes over the next few weeks/months.  As such, I'm going to close this out.

Thanks again.
