### ISSUE TITLE
Extension cannot be enabled on MacOS BigSur!

### ISSUE THREAD

**Issue by iMonZ** [duckduckgo/privacy-essentials-safari#4]
Hey,

after enabling this extension(Privacy Dashboard) I get this error Message:

[Screenshot 2020-09-02 at 11.33.15.zip](https://github.com/duckduckgo/privacy-essentials-safari/files/5161367/Screenshot.2020-09-02.at.11.33.15.zip)

MacOS Version: 11.0 Beta (20A5354i)

**Comment by brindy** [comment]
Hi, thanks for this! We'll investigate.

**Comment by brindy** [comment]
Hi, just wondering if you're still seeing this on more recent betas?  

We've been focussing on iOS just now but should be able to get to this soon.  Thanks!

**Comment by samsymons** [comment]
Hey @iMonZ, thanks for reporting this! Now that Big Sur's been out for a while and we haven't seen any more reports, I'm going to close this ticket. Please do let us know if you run into any other trouble.

Thanks again!

**Comment by iMonZ** [comment]
> Hi, just wondering if you're still seeing this on more recent betas?
> 
> We've been focussing on iOS just now but should be able to get to this soon. Thanks!

Yes that is the case
