### ISSUE TITLE
Safari crashes

### ISSUE THREAD

**Issue by psuryan** [duckduckgo/privacy-essentials-safari#8]
Has happened few times this week alone. Console logs below. 

Process:               Safari [9124]
Path:                  /Applications/Safari.app/Contents/MacOS/Safari
Identifier:            com.apple.Safari
Version:               14.0.2 (16610.3.7.1.9)
Build Info:            WebBrowser-7610003007001009~1
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Safari [9124]
User ID:               501

Date/Time:             2021-01-03 04:32:19.856 -0500
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Bridge OS Version:     5.1 (18P3030)

Time Awake Since Boot: 800000 seconds
Time Since Wake:       300000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace ASSERTIOND, Code 0xd00d2bad

Application Specific Information:
Enabled App Extensions:
com.duckduckgo.macos.PrivacyEssentials.SafariAppExtension (HKE973VLUW) (Version: 14 - Display Version: 1.4.3) Privacy Dashboard

**Comment by tomasstrba** [comment]
Hey @psuryan, thanks for the submission of this issue! The extension usually doesn't crash whole Safari. Seems the crash is related to Safari extension API and uncovers some internal problem. There are similar reports for other extensions too. We'll monitor that and let you know. Thanks again! 👍

**Comment by samsymons** [comment]
Hey @psuryan, we suspect this was a macOS bug that has since been resolved. Let us know if you're still seeing crashes, but otherwise I'm closing this out. Thanks for the report!
